### ISSUE TITLE
Lifecycle of stream separate from lifecycle of camera

### ISSUE THREAD

**Issue by gitonthescene** [MABelanger/jslib-html5-camera-photo#16]
Hi there.  First, thanks for this lib.  I wanted to use it as is for a react app that I was building ( before I saw react-html5-camera-photo ).  One issue I ran into is that when the camera was embedded in a page with other elements it made new streams with every re-render.  Since the camera constructor takes a video element, it needs to be re-created each time the video element is mounted, which in turn means creating a new stream each time the video element is mounted and this is relatively heavy-weight.

I would like to be able to write code like the following so that the lifecycle of the stream is handled as state of my component rather than be owned by the camera:

```
 const [ stream, setStream ] = useState( undefined );
  ...
   const initVideo = (el)=> {
    if ( el === null ) {
      video = undefined;
      camera = undefined;
      return;
    }
    video = el;
    camera = new CameraPhoto( video );
    camera.startCamera(stream)
      .then( (strm) => { setStream( strm ); } )
      .catch( (e) => openDialog( 'Could not initialize video', e.message ) );
  };
  ...
  return (
      <div>
        <video
          ref={initVideo}
        />
   );
```

I've already forked the code to prepare a pull request, but saw you'd asked to create an issue first.

Please let me know what you think.  I'll have a look at react-html5-camera-photo.

Regards,
-Doug

**Comment by MABelanger** [comment]
Why do you want a new stream ? The stream is binded to the camera so they is no way to create new stream without restarting the camera. The code above will trigger rerender each time you do setState so you should use useRef for the stream state. I will close this issue, feel free to reopen it.

**Comment by gitonthescene** [comment]
This is a very old issue so I’m okay with whatever you want to do here, but just to clarify,  I _don’t_ (or rather didn’t) want a new stream but was getting one every time the element was re-rendered, which was pretty regularly in the React element I was working on at the time.

This issue is old enough that I’m not following what you mean when you say “use useRef for the stream state” but the whole point of the original post was to manage the stream independent of the Camera object which is otherwise fairly lightweight.
