### ISSUE TITLE
Responsive Video Size but Low Resolution

### ISSUE THREAD

**Issue by jason050196** [MABelanger/jslib-html5-camera-photo#21]
As long as we want the image size larger, we just need to set the video size be such as:
style={{
    width: "1000px",
    height: "1000px"
}}
but as I'm building my react app with responsive size for mobile, I have set the width to 100% of screen(window, ~350px) width, but then the resolution of the output image is quite low.

Is there a fix for responsive video preview but a high resolution such as 1000px width?

**Comment by MABelanger** [comment]
hi @jason050196 , it's supposed to have the same resolution as the camera, is not related to the css of the canva video. So even you set the css as 1px width and height, the dataUri will be the same width and height unless you specify the sizeFactor < 1
