### ISSUE TITLE
ViewFinder

### ISSUE THREAD

**Issue by patv2learn** [MABelanger/jslib-html5-camera-photo#23]
Hey, first of all thanks for the great library and clean code. But having q question, is there anyway this can be enhance with ViewFinder feature? I am looking to capture a document from phone camera but wanted to give ViewFinder kind of effect what in general native camera app provides.

I have attached an example of what kind of option I wanted to add.
![card_scan](https://user-images.githubusercontent.com/27989386/84586160-db73ff00-adcb-11ea-8b3c-b89a31ad75a9.gif)

Thanks.

**Comment by dobesv** [comment]
Did you try putting a semi-transparent overlay on top of the camera component?

**Comment by patv2learn** [comment]
Sorry, but I was not able to get this result. I did try many other samples but with no success. Please share any article/post/code snip you can. Thank you.

**Comment by MABelanger** [comment]
You need to css the video html element. Probably some thing like : https://stackoverflow.com/questions/26013062/apply-a-responsive-svg-image-mask-to-a-html5-video
I will close this issue.
