### ISSUE TITLE
advanced media constraints do not seem to work in iOS 13 Safari

### ISSUE THREAD

**Issue by mweibel** [MABelanger/jslib-html5-camera-photo#25]
Thanks for the library. 

Currently [max constraints](https://github.com/MABelanger/jslib-html5-camera-photo/blob/dafa2f415caf4d0728743aae69285707c4c21ab9/src/lib/MediaServices/index.js#L138) rely on [advanced constraints](https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints#Advanced_constraints) which you correctly outline as having problems (in [CONTRIBUTING.md](CONTRIBUTING.md)). 

In iOS Safari using get max constraints results in having the minimum (640x480) resolution selected. Which is quite the opposite what we might want ;) 
A possibility would be the following:

```diff
diff --git a/src/lib/MediaServices/index.js b/src/lib/MediaServices/index.js
index 1b8e767..f7ee4a4 100644
--- a/src/lib/MediaServices/index.js
+++ b/src/lib/MediaServices/index.js
@@ -114,7 +114,10 @@ class MediaServices {
   }

   static getMaxResolutionConstraints (idealFacingMode = {}, numberOfMaxResolutionTry) {
-    let constraints = MediaServices.getIdealConstraints(idealFacingMode);
+    let constraints = MediaServices.getIdealConstraints(idealFacingMode, {
+      width: { min: 640, ideal: 3840 },
+      height: { min: 480, ideal: 2160 }
+    });
     const facingMode = constraints.video.facingMode;

     const VIDEO_ADVANCED_CONSTRANTS = [

```

(That's just what I hacked in - of course an actual change would get rid of the advanced constraints part).
I.e. set the constraint to be maximum what you might possibly want and minimum to the minimum - the phone's camera will then take what is correct.
Confirmed this works on iOS 13 Safari and FF 80 / Chrome 84 (Desktop).

**Comment by MABelanger** [comment]
Thank you for your feedback.
I did a fix for the max resolution, i hope it will work in ios and other platform as it intended ;)

https://github.com/MABelanger/jslib-html5-camera-photo/pull/69

Can you confirm that fix work with your devices ?
Check the demo : https://mabelanger.github.io/jslib-html5-camera-photo/
and click on startMaxResolution it should be greater than 640x480
