### ISSUE TITLE
Choose specific camera

### ISSUE THREAD

**Issue by dobesv** [MABelanger/jslib-html5-camera-photo#34]
In apps like Google Meet I can specifically choose a camera by name on my PC.

When I use this library, I can't choose the camera.  I can't even change cameras using the video camera selection in the navigation bar.

Any idea whether it's possible to show the user a list of video inputs and let them choose the one they want?

**Comment by Aarbel** [comment]
@dobesv have you found a way to achieve this ?

**Comment by MABelanger** [comment]
Hello,
please check the new version @3.1.10

Thank for feedback.
