### ISSUE TITLE
Memory leak on Safari/iOS?

### ISSUE THREAD

**Issue by perusopersonale** [MABelanger/jslib-html5-camera-photo#40]
I'm using this library to build an app that require to take a lot of photos and its main target are mobile phones. I was using react-html5-camera-photo, the app works very fine in Android/Chrome, but on Safari/iOS there was a lot of crash. 

The flow of the app is take a photo, confirm photo, take next photo, confirm next photo and so on. What I was doing was open camera, take photo, close camera, for each photo required, this, for some obscure reason, on Safari makes the app consume more and more memory until the inevitable crash. I don't know if this problem is related to this lib or to Safari, I didn't dig too much, but to prevent this I had to keep the camera always open.

**Comment by MABelanger** [comment]
Hi @perusopersonale,
yes the best approch is to keep the camera open until you close the page. I don't know eather why safari crash when you reload multiple time the camera. Make sure that 

```js
let cameraPhoto = new CameraPhoto(videoElement);
```
is not instanciate many time, put it in the parent and use startCamera() an stopCamera() in the children.

I will close the issue, feel free to reopen it if you find some thing.
thank
