### ISSUE TITLE
use of other constraints like focusMode

### ISSUE THREAD

**Issue by Ridder90** [MABelanger/jslib-html5-camera-photo#44]
Hi there!

I was wondering if there is a possibility to overwrite or add other constraints. Like for example the focusMode constraint. I would like to set it to `single-shot` 

Thnx!

**Comment by MABelanger** [comment]
Hi @Ridder90, 
Hum, right now, it only take camera device and resolution as constraints. Maybe it can be a good idea to add a third parameter with `other constrints`.  I will close the issue, Thank for feedback I will notify you when i add it.
