### ISSUE TITLE
Wait until video reference is ready in hook

### ISSUE THREAD

**Issue by boris-ravas** [MABelanger/jslib-html5-camera-photo#52]
We are using hook similar to yours [useLibCameraPhoto.js](https://github.com/MABelanger/react-html5-camera-photo/blob/master/src/lib/components/Camera/hooks/useLibCameraPhoto.js) and sometimes we got an issue. Problem is with videoRef which is passed to the library constructor in useEffect. Sometimes the videoRef is not ready yet, so it has videoWidth and videoHeight equal 0.

Is there a way how to 'await' the videoRef in hook to be ready and has videoWidth and videoHeight set?

Thanks for any tips or advises.

**Comment by MABelanger** [comment]
Have you tried 
```  
useEffect(() => {
    if (videoRef && videoRef.current) {
      libCameraPhoto = new LibCameraPhoto(videoRef.current);
    }
  }, [videoRef]);
```
?

**Comment by MABelanger** [comment]
Have you tried 
```  
useEffect(() => {
    if (videoRef && videoRef.current) {
      libCameraPhoto = new LibCameraPhoto(videoRef.current);
    }
  }, [videoRef]);
```
?

**Comment by MABelanger** [comment]
I will close this issue, because it's not related to this lib, thank
