### ISSUE TITLE
Why is broadcast taking over the screen now?

### ISSUE THREAD

**Issue by mininglink** [MABelanger/jslib-html5-camera-photo#54]
what has changed with the API that is causing the broadcast to come up when we access the camera

Is there a setting we need to change

current config 

<video
  width={ width }
  height={ height }
  ref={this.videoRef}
  autoPlay={true}
/>

![image](https://user-images.githubusercontent.com/3881064/133730204-02da8f38-add3-43c3-b93f-7eafb6f853a0.png)

![IMG_CDC0414F771C-1](https://user-images.githubusercontent.com/3881064/133729470-892d78d0-888e-47db-b813-21878781b227.jpeg)

**Comment by vivianlys90** [comment]
Having same issue in iOS. Any update for this issue?

**Comment by MABelanger** [comment]
Hi,
It probably not related to the lib maybe it's the video tag that missing attribute
```
<video autoplay="true" playsinline=""></video>
```
Please checkout if it's work with : https://mabelanger.github.io/jslib-html5-camera-photo/

Feel free to reopen the issue if the link do not work.
