### ISSUE TITLE
How to run on browser

### ISSUE THREAD

**Issue by ChrisInv** [MABelanger/jslib-html5-camera-photo#6]
Hello,

how can I run this on a browser, without using any framework like React? What files do I need to include in `<script>` tags, and how exactly?

The demo looks awesome, so thanks for this!

**Comment by MABelanger** [comment]
Hi,
Right now you can use the demo link already compiled :https://mabelanger.github.io/jslib-html5-camera-photo/static/js/main.1b0d5813.js i suggest to download the script because in each update the link will change... I think it exist an CDN for npmjs but i don't know the address... If you find it please let me know... So for now i only check inside the demo index.html the link of the <script>

**Comment by ChrisInv** [comment]
Hi,

Thanks for the reply. However, the compiled code contains functions and listeners specific for your demo, which won’t work for any other integration.

Is the next update any time soon? Do you think you will be able to release the code to be more generic so it can be integrated to other projects?

Thanks again!

Hi,
Right now you can use the demo link already compiled :https://mabelanger.github.io/jslib-html5-camera-photo/static/js/main.1b0d5813.js i suggest to download the script because in each update the link will change... I think it exist an CDN for npmjs but i don't know the address... If you find it please let me know... So for now i only check inside the demo index.html the link of the <script>

**Comment by MABelanger** [comment]
Hello,
Sorry i did not found a solution, i work with webpack that buldle my js. I deleted my comment because i  realize 5 min after posted my comment of what you told ;) Can you try : https://unpkg.com/jslib-html5-camera-photo ?

**Comment by MABelanger** [comment]
If it does not work we need to check how to do that maybe : https://webpack.js.org/guides/author-libraries/

**Comment by MABelanger** [comment]
Hi @ChrisInv 
Ok the lib is now compatible UMD (Universal Module Definition) so you can use with <script> tag.
to build the module you can do 

> yarn buildBrowser

I commited the **/dist** generated by the build so you can use it. Check the **[index.html](/MABelanger/jslib-html5-camera-photo/blob/master/dist/index.html)** to know how to use it.

## In your HTML: 
```
<script src="/jslib-html5-camera-photo.min.js"></script>
<script>
  ...
  var FACING_MODES = JslibHtml5CameraPhoto.FACING_MODES;
  var cameraPhoto = new JslibHtml5CameraPhoto.default(videoElement);
  ...
</script>
```
