### ISSUE TITLE
[iOS] Using the startCameraMaxResolution uses Default Resolution instead of Max

### ISSUE THREAD

**Issue by A-Matt** [MABelanger/jslib-html5-camera-photo#64]
Got a project where we use the startCameraMaxResolution and has been working lovely on our Android Devices.
However the photos which have been produced by iOS devices are all constantly been 480p which seems to be the "default" resolution which they output for on the browser.

Manually setting the camera's output will allow for us to successfully get bigger pictures outputted.

**Comment by MABelanger** [comment]
Thank you for your feedback.
I did a fix for the max resolution https://github.com/MABelanger/jslib-html5-camera-photo/pull/69

Can you confirm that fix work with your devices ?
Check the demo : https://mabelanger.github.io/jslib-html5-camera-photo/
and click on startMaxResolution it should be greater than 640x480

**Comment by Alipoodle** [comment]
👍 will take a look into updating the lib in our tools and get back soon.
