### ISSUE TITLE
Camera not started! TypeError: Cannot use 'in' operator to search for 'srcObject' in undefined

### ISSUE THREAD

**Issue by GuiRitter** [MABelanger/jslib-html5-camera-photo#7]
Hi everyone.

I was writing this issue when I realized my code was wrong. But still, I feel like this library's error treatment could be better, so I'll continue posting as I was originally going to.

---

I'm testing out this library. I'm integrating it in React. I'm rendering an element like this:
```js
<video ref={ref => {
    if (ref) {
        this.videoElement = ref;
    }
}} autoPlay playsInline></video>
```
And I'm starting the camera like this:
```js

componentDidMount() {
    this.cameraPhoto = new CameraPhoto(this.videoRef); // intentionally wrong ref, should be this.videoElement
    this.cameraPhoto.startCamera(FACING_MODES.ENVIRONMENT, {})
        .then(() => {
            console.log('camera is started !');
        })
        .catch((error) => {
            console.error('Camera not started!', error);
        });
}
```
I've launched my app with `set HTTPS=true&& npm start`, accessed it from my Android and I am inspecting it with Chrome DevTools remotely (connected via USB). When this component loads, I get the error in the title.

I've enclosed the lines starting [here](https://github.com/MABelanger/jslib-html5-camera-photo/blob/39135c26ac084d1a01e8fb925085381ace1e45d6/src/lib/index.js#L69) and ending [here](https://github.com/MABelanger/jslib-html5-camera-photo/blob/39135c26ac084d1a01e8fb925085381ace1e45d6/src/lib/index.js#L75) with
```js
if (this.videoElement) {
    ...
}
```
It doesn't throw errors, says `camera is started !` but still doesn't work, showing a 300×150&nbsp;px white element.

**Comment by kouohhashi** [comment]
I think this happens because this.videoRef is not set properly.
You can set ref simply by,
```
componentDidMount() {
  this.cameraPhoto = new CameraPhoto(this.refs.videoRef);
}
```

And in render()
```
<video
  ref="videoRef"
  autoPlay="true"
/>
```

It worked for me.

Thanks.

**Comment by MABelanger** [comment]
I think @GuiRitter  mean that if a wrong ref passing as argument constructor of the lib like `new CameraPhoto(this.wrongRef)` have to throw an error when we start the camera with a wrong ref. Is that what you mean?

**Comment by GuiRitter** [comment]
> I think @GuiRitter mean that if a wrong ref passing as argument constructor of the lib like `new CameraPhoto(this.wrongRef)` have to throw an error when we start the camera with a wrong ref. Is that what you mean?

Yup, that's it. Or something similar.

**Comment by kouohhashi** [comment]
Sorry guys. I got same error and I thought reason and a possible solution
may be helpful because error message don't tell the reason as you mentioned.

**Comment by gitonthescene** [comment]
It looks like @GuiRitter is using a callback ref: https://reactjs.org/docs/refs-and-the-dom.html#callback-refs.

Note that the callback is called on unmounting as well and so some extra care must be taken.

"React will call the ref callback with the DOM element when the component mounts, and call it with null when it unmounts. Refs are guaranteed to be up-to-date before componentDidMount or componentDidUpdate fires."
