### ISSUE TITLE
startCameraMaxResolution with facing mode FACING_MODES.USER open back camera on iOS

### ISSUE THREAD

**Issue by leolelego** [MABelanger/jslib-html5-camera-photo#8]
Using this code open the front camera on mobile devices, as requested 

```
this.cameraPhoto = new CameraPhoto( this.videoElement);
 this.cameraPhoto.startCamera(FACING_MODES.USER)
        .then(() => {
            console.log('Camera started !');
            let cameraSettigs = this.cameraPhoto.getCameraSettings();
            if (cameraSettigs) {
                let {aspectRatio, frameRate, height, width} = cameraSettigs;
                if (height < 640 || width < 480) {
                    this.stopCamera()
                    alert("You device haven't an enought good camera to use this feature." + height + "/"+width)
                }
            }
        })
        .catch((error) => {
            alert("your camera can't be opened :" + error)
            console.error('Camera not started!', error);
        });
```

But the same code with `startCameraMaxResolution` open always the back camera on iOS. Tested on iPhone and iPad on multiple models.

**Comment by MABelanger** [comment]
Ok thank for the report

**Comment by MABelanger** [comment]
Hi @leolelego 
Can you try this fix ?
Thank

**Comment by darekg11** [comment]
Can you rebuild the `dist` directory with that fix so that it can be used by vanilla JS user? I am facing this error and I would like to test it out on my vanialla JS website where I need it. Also could you add section to README describing how one could build this library by himself?

**Comment by MABelanger** [comment]
yes [import-the-umd-module-with-html-script-tag](https://github.com/MABelanger/jslib-html5-camera-photo#import-the-umd-module-with-html-script-tag)
